bash1:
	sudo vi ~/.bashrc
bash2:
	sudo vi ~/.zshenv
bshp:
	sudo vi ~/.bash_profile
install:
	brew install tree && brew install wget
py:
	sudo chmod 755 py.sh &&	./py.sh
pip:
	sudo chmod 755 pip.sh && ./pip.sh
sshgen:
	sudo chmod 755 sshgen.sh && ./sshgen.sh

